### PR TITLE
localization update

### PR DESCRIPTION
**Pull request by ToastyStoemp**
Some suggested changes for English text.

### CODE REVIEW

**Comment by ToastyStoemp** [comment]
Don't merge just yet, I have't been able to get the linter working on my instance. Temp on HOLD

**Comment by yoichiro** [comment]
@ToastyStoemp Sorry for the late, I noticed your comment just now, and the CI task was executed. Unfortunately, it was failed. Could you fix it?

**Comment by yoichiro** [comment]
@ToastyStoemp If you can't execute a formatter on your local environment, I can execute the formatter and merge this. Feel free to let me know if you can't prepare your local environment or the formatter is failed.

**Comment by ToastyStoemp** [comment]
Was able to get format to working on Linux distro I do appreciate you spending time trying to help fix the PR

**Review by yoichiro — APPROVED** [review]
@ToastyStoemp LGTM! Thank you for your contribution!

**Pull request merged**
