### PR TITLE
Edit keymap with keyboard

### LINKED ISSUE #702: [Feature Request] Edit keymap with keyboard
I want to edit keymap with keyboard. 

My suggestion is following change for keymap editor:
- `selectedPos` is not cleared when the custom key popup is closed
- Keymap setting is updated on keydown events. New key setting is generated from pressed key.
- Automatically select next key

### PR DESCRIPTION
**Pull request by sekigon-gonnoc**
This pull request enables editing keymap with keyboard.

Resolves #702

### CODE REVIEW

**Comment by yoichiro** [comment]
@sekigon-gonnoc I checked some behaviors before reviewing the code. For example, when typing `Q` on the `Q` key, 

Screenshot_20220322_122034

my expected behavior is that the key doesn't change anything. However, Remap displayed that the key has been changed.

Screenshot_20220322_122111

I think that the correct behavior is that the `Q` key is not be changed.

How do you think about this?

**Comment by yoichiro** [comment]
@sekigon-gonnoc For example, when trying setting the `_` key by pressing `SHIFT+-` physical key binding,

Screenshot_20220322_123930

Instead of setting the `_` character, but `*shift` was set. This behavior is not my expected behavior.

Is the actual behavior your expected behavior?

**Comment by sekigon-gonnoc** [comment]
> I checked some behaviors before reviewing the code. For example, when typing `Q` on the `Q` key,
> 
> my expected behavior is that the key doesn't change anything. However, Remap displayed that the key has been changed.
> 
> I think that the correct behavior is that the `Q` key is not be changed.
> 
> How do you think about this?

I fixed this in the latest commits.
Now keys aren't updated if pressed key is same as current keymap.

**Comment by sekigon-gonnoc** [comment]
> For example, when trying setting the _ key by pressing SHIFT+- physical key binding,
> Instead of setting the _ character, but *shift was set. This behavior is not my expected behavior.
> Is the actual behavior your expected behavior?

Currently, yes, this is expected behavior. I implemented this for basic 'without mods' and 'single mod' keycodes.
A simple idea for improvement is:

- update keymap and count pressed keys on keydown events, 
- then select next key if all keys are released on keyup events.

This may make it possible to set some symbol keycodes.
Do you have any ideas?

**Comment by yoichiro** [comment]
@sekigon-gonnoc Thank you for the idea. Well, I have decided that I respect your implementation and your original idea. Therefore, I intend to release your code. After that, if we receive some feedback, we can discuss about them.

I will merge this pull request after changing some logic and structures.

**Pull request merged**
